#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

require __DIR__ . '/vendor/autoload.php';

$status = require_once __DIR__ . '/bootstrap/app.php';

exit(is_numeric($status) ? $status : 0);
